site_name: OpenLISEM
docs_dir: source

theme:
  name: readthedocs

nav:
  - Home: Home.md
  - Getting started: Getting-started.md
  - Manual: Manual.md
  - Tutorials: Tutorials.md
  - Theory: Theory.md
  - History: History.md
  - About: About-OpenLISEM.md