site_name: OpenLISEM
docs_dir: source

theme:
  name: readthedocs

plugins:
    - awesome-pages:
        filename: .pages
        collapse_single_pages: false
        strict: false
        order: asc
        sort_type: natural
        order_by: title
    - search

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML