IF(UNIX AND NOT CYGWIN)
    SET(CMAKE_SKIP_BUILD_RPATH FALSE)
    SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
    SET(CMAKE_INSTALL_RPATH "${CMAKE_INSTALL_PREFIX}/lib")
    SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH FALSE)
ENDIF()


INCLUDE(CheckCXXCompilerFlag)

IF(${CMAKE_CXX_COMPILER_ID} STREQUAL "GNU" OR
        ${CMAKE_CXX_COMPILER_ID} STREQUAL "Clang")
    SET(CMAKE_CXX_FLAGS
        "${CMAKE_CXX_FLAGS} -Wall -liconv -Wextra -Wcast-qual -Wwrite-strings -Werror=strict-aliasing -std=c++11 -pedantic"
    )
ENDIF()

# Add the PIC compiler flag if needed.
IF(UNIX AND NOT WIN32)
    IF(CMAKE_SIZEOF_VOID_P MATCHES "8")
        CHECK_CXX_COMPILER_FLAG("-fPIC" WITH_FPIC)
        IF(WITH_FPIC)
            ADD_DEFINITIONS(-fPIC)
        ENDIF()
    ENDIF()
ENDIF()
